### ISSUE TITLE
Allow specifying working directory pylint job

### ISSUE THREAD

**Issue by swarminglogic** [leinardi/pylint-pycharm#17]
**Is your feature request related to a problem? Please describe.**
`pylint` automatically adds the cwd to the python path.

`pylint-pycharm` does not seem to allow configuring this path, and makes it difficult to avoid false positive `import-error` issues.

**Describe the solution you'd like**
It would be great to be able to set this value on a per-project basis.

**Comment by leinardi** [comment]
Hi @swarminglogic, this seems related to #7, could you please try the build available [here](https://github.com/leinardi/pylint-pycharm/issues/7#issuecomment-419642617) and let me know if that solve your issue?

**Comment by leinardi** [comment]
Hi @swarminglogic, could you please test v0.10.0 and let me know if it fixes this issue?
