### ISSUE TITLE
Absolute pylint path not working in windows environment

### ISSUE THREAD

**Issue by LLcoolNJ** [leinardi/pylint-pycharm#22]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the plugin.

### Step 2: Describe your environment
 - Plugin version: `0.10.0`
 - PyCharm/IDEA version: `2018.2.1`
 - Pylint version: `2.1.1`
 - Platform: `Windows`

#### Steps to reproduce:

  1. Give path to pylint executable in settings and test it. It should return "executable not found".

#### Observed Results:

  * throws error "Failure: executable not found".
  

#### Expected Results:

  * It should return "Success: executable found".

**Comment by leinardi** [comment]
Hi @LLcoolNJ, thank you for your PR, currently I cannot test the plugin on Windows, are you aware of any other issue on this OS?
As far as I know the autodetection of the executable is not working but I have some ideas on how to fix it... would you be available to test some dev builds?

**Comment by LLcoolNJ** [comment]
Hi @leinardi , I have tested it on windows. It is working fine. I have not faced any issue in it.
Sure, I can test dev builds for autodetection.
