### ISSUE TITLE
PyLint auto-detection not working on Windows

### ISSUE THREAD

**Issue by leinardi** [leinardi/pylint-pycharm#24]

**Comment by taljaards** [comment]
@leinardi has this issue been completely solved?
Using the latest release from PyCharm's repository of plugins, I get this error with the plugin where it says that it cannot locate Pylint.exe
However, Pylint is installed and at that location...

![image](https://user-images.githubusercontent.com/6089256/45994098-70801300-c092-11e8-9640-5dbea66b58bb.png)

**Comment by leinardi** [comment]
Hi @taljaards, do you see any error being reported inside the Event log when that message is shown? Could you please send me the idea.log file (https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) after you get the "Failure: executable not found error"?

**Comment by taljaards** [comment]
Hi. This is what I get in the Event Log in PyCharm itself:
```
2018/09/25
12:27	Pylint Plugin: Failure: executable "C:\Users\Admin\AppData\Local\Continuum\anaconda3\Scripts\pylint.exe" not found
```
And then [this](https://pastebin.com/6JKZn6Qk) is my latest IDE log file.

**Comment by leinardi** [comment]
Mmm, inside the log file I see this error:
```
ava.lang.Throwable: Error while checking Pylint path:   File "C:\Users\Admin\AppData\Local\Continuum\anaconda3\Scripts\pylint.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file C:\Users\Admin\AppData\Local\Continuum\anaconda3\Scripts\pylint.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

If I get it right, the version of PyLint for Windows that you are using is not specifying the encoding properly.

Can you try to run manually this command in a Windows Shell to see if we can reproduce the issue?
```
C:\Users\Admin\AppData\Local\Continuum\anaconda3\python.exe C:\Users\Admin\AppData\Local\Continuum\anaconda3\Scripts\pylint.exe --help-msg E1101
```

And, if you are getting the same error, can you try to run this to see if you get something different?
```
C:\Users\Admin\AppData\Local\Continuum\anaconda3\python.exe -m C:\Users\Admin\AppData\Local\Continuum\anaconda3\Scripts\pylint.exe --help-msg E1101
```

**Comment by taljaards** [comment]
```
2018/09/25
14:00	Pylint Plugin: Success: executable found!
```
It's fixed in your dev build 😊

**Comment by leinardi** [comment]
Glad to hear, I will release a new version soon with this fix :+1:.

**Comment by whg517** [comment]
Hi, I have this problem today.

- Windows 10
- PyCharm 2018.3.5 (Professional Edition) Build #PY-183.5912.18, built on February 26, 2019
- Plugin version: v0.11.0 (Pycharm automatic installation)
- pylint: 2.3.0 (latest version)

The Python interpreter is a virtual environment generated by pipenv.

![](https://markdown-photograph.oss-cn-hangzhou.aliyuncs.com/pylint_pycharm_plugin_error.png)

**Comment by Srinuthalapati** [comment]
Exactly same issue, for me as well, even though the pylint.exe is present in that folder:

Pylint Plugin: Failure: executable "C:/Users/shanmuga.nuthalapati/Desktop/CCoE-MyTeam/ESS/Current Repositories/NEXT/sawtooth-next-directory/ENV/Scripts/pylint.exe" not found

**Comment by alfRep** [comment]
If you are getting a plugin failure, ensure your .pylintrc file is correct. I had an incorrectly named parameter and it caused this error.

**Comment by satmahesh** [comment]
I am trying to run pylint file from Bamboo getting below error

Unable to find executable at C:/Users/MaheshSathe/AppData/Local/Programs/Python/Python37-32/python.exe. Will try to run it anyway.
-- | --

**Comment by fahad80** [comment]
@dixong Thanks. That worked!

**Comment by smye** [comment]
@dixong Thanks - that fixed it for me
