### ISSUE TITLE
Failure: executable "/usr/local/bin/pylint" not found

### ISSUE THREAD

**Issue by StevenMapes** [leinardi/pylint-pycharm#34]
- Plugin version: 0.10.2
- PyCharm/IDEA version: 2018.3
- Pylint version: 2.1.1

  1. Install pylint3 globally (apt-get remove pylint3) or pip3 install pylint
  2. Install this plugin
  3. Restart Pycharms
  4. Open pycharms,  go to file->settings->Pylint and set path to /usr/local/bin/pylint
  5. Click test

#### Observed Results:
Failure: executable "/usr/local/bin/pylint" not found
  
#### Expected Results:
Ok

#### Debugging
Confirm pylint location
```
>>>  which pylint
/usr/local/bin/pylint
```
Confirm pylint runs
```
>>> pylint --version
pylint 2.1.1
astroid 2.0.4
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
```

**Comment by leinardi** [comment]
Hi @StevenMapes, have you set an interpreter for the PyCharm project? If yes, is it the same where PyLint is installed?

**Comment by StevenMapes** [comment]
Ah no, it's using a VENV whereas pylint is installed globally. Does it need to be installed into the venv then?

**Comment by leinardi** [comment]
Yep, I should probably make it more clear but, unfortunately, PyLint must be installed in the same environment that is used for the PyCharm project.

**Comment by asyschikov** [comment]
@leinardi are there any particular reasons why pylint must be in the same env? I don't see a point in installing pylint in every env I use (dozens of them).

**Comment by leinardi** [comment]
Yes, the reason is that Pylint will look for the dependencies of the code that is analyzing in the same environment where it is executed so, if you run it on the system environment, you must have there all the dependencies of all your project, which can be very tricky if you need different versions of the same module for different projects.

**Comment by asyschikov** [comment]
@leinardi thanks for the explanation, makes sense.

**Comment by zwn** [comment]
I can run pylint installed with pipx from the command line. I understand it might be better to install it in the same venv as the project, but it can be run never the less. Can we make it work for the plugin as well?

**Comment by fzyzcjy** [comment]
I am facing the same problem in https://github.com/leinardi/pylint-pycharm/issues/89. Could you please provide some suggestions?

**Comment by ewagner-verta** [comment]
I'm having the same problem.  

Pylint is definitely installed in my pyenv virtual environment (also the project interpreter)
<img width="999" alt="Screen Shot 2023-02-02 at 11 08 05 AM" src="https://user-images.githubusercontent.com/114943931/216408821-8dee9e83-860a-4a31-a62a-bbbe2354f0f7.png">

I am using that location as the path to the executable
<img width="1443" alt="Screen Shot 2023-02-02 at 11 08 40 AM" src="https://user-images.githubusercontent.com/114943931/216409023-19de427f-5f3d-460b-acf3-c4ef997178ab.png">

which I have confirmed exists
![Screen Shot 2023-02-02 at 11 12 56 AM](https://user-images.githubusercontent.com/114943931/216409975-b1c155eb-39ce-4a1a-bc2a-888e1bcec37d.png)

But still, this error:
<img width="391" alt="Screen Shot 2023-02-02 at 11 11 37 AM" src="https://user-images.githubusercontent.com/114943931/216409461-f581ecee-5576-403b-b553-a2c3bbed7379.png">
