### ISSUE TITLE
Plugin does not show problems, but on CLI problems are shown

### ISSUE THREAD

**Issue by flashpixx** [leinardi/pylint-pycharm#38]
My environment:

* PyCharm 2018.3
* Plugin version 0.10.2
* Pylint version 2.2.2 with [configuration](https://gitlab.com/mind-manufacture/artificial-intelligence/blob/master/.pylintrc)
* Python 3.6.7 with Pyenv on OSX 10.14

* _Problem 1:_ pylint shows "Pylint found no problem", although pylint shows errors on the command-line. I run at the commandline ```pylint mymodule``` so I have configured the Àrguments`with `mymodule`, path to pylintrc is empt and the auto-detected pylint version is correct found under ```~/.pyenv/versions/3.6.7/bin/pylint```
* _Problem 2:_ The plugin expected a file named ```pylintrc``` but on command-line pylint expected a file named ```.pylintrc``` (with a dot at the beginning), so it should be nice if the plugin tries to read both files or I would be possible to configurate the pylint filename not the path. For my testings I add a symlink to my ```.pylintrc```

![bildschirmfoto 2019-01-21 um 22 51 45](https://user-images.githubusercontent.com/1868222/51500692-45eb6000-1dcf-11e9-8800-265d939d7950.png)

**Comment by flashpixx** [comment]
Reinstall PyCharm with removing configuration and reinstalling plugin solves the problem

**Comment by bjackson** [comment]
Same thing happens for me, but reinstalling the plugin doesn't help.
