### ISSUE TITLE
On Windows allow pylint to use pylint installed in WSL

### ISSUE THREAD

**Issue by ashwinkapur** [leinardi/pylint-pycharm#58]
**Is your feature request related to a problem? Please describe.**
I use this plugin on IntelliJ and Pycharm under Windows. My python interpreter and virtual environments are all on WSL, a linux environment that runs under Windows 10. This plugin (and the mypy plugin cannot use a pylint installed in WSL. I give it the right path but I get an error that it cannot execute.

**Describe the solution you'd like**
Enable the use of pylint installed under WSL when running in Windows (and ideally using a remote interpreter)

**Describe alternatives you've considered**
1) Install python 3.8.1 on windows, the windows version of pipx and then pylint.exe in windows using pipx. This sort of works but then pylint cannot find the packages I'm using in each project. So I have to manually activate the virtual environment pipx has created for pylint and then install the packages I need under that.

2) 1 is no better than creating a windows based virtual environment and installing pylint in that so I'm not doing this. I basically create a linux virtual environment under WSL and a regular Windows virtual environment only for pylint and mypy. Still not great because there are some python packages that I use that cannot be installed under Windows and pylint (and mypy) will complain due to them being missing.

**Additional context**
Ideally you would come up with a general solution that will work with remote python interpreters. Basically I would like to be able to install pylint (and mypy) under a python interpreter on a remote machine and have this plugin use that pylint and mypy when I'm working with a python interpreter on a remote machine.

**Comment by ashwinkapur** [comment]
And thank you for a great plugin.

**Comment by maspe36** [comment]
Was about to create this issue myself, this is definitely something that would be helpful.

**Comment by cristian05** [comment]
Something new about this?

**Comment by benoit-dubreuil** [comment]
> No Python interpreter configured for the project.

when I use a Python interpreter installed in my WSL Ubuntu.

**Comment by mnogokotin** [comment]
I need this feature too )

**Comment by Xoma163** [comment]
+
