### ISSUE TITLE
Pylint Plugin: Failure: executable "/usr/bin/pylint" not found

### ISSUE THREAD

**Issue by MrBerthier** [leinardi/pylint-pycharm#80]
### Step 1: Are you in the right place?
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of the plugin.

### Step 2: Describe your environment
 - Plugin version: 12.2
 - PyCharm/IDEA version: 2020.3
 - Pylint version: 1.8.3

#### Steps to reproduce:

When I start a Pylint check on the current file, I got the following error message : **_"Pylint Plugin: Failure: executable "/usr/bin/pylint" not found"_**

For information, my project interpreter is **_/usr/bin/python3.6_** and I am not using any venv.

#### Observed Results:

  * When I run Pylint in command line in a terminal, it works great.

  * When I go to the plugin settings, **_Path to Pylint executable_** displays **_Auto-detected: /usr/bin/pylint_**

  * When I click on the button test, I got an error notification telling me that the executable **_/usr/bin/pylint_** is not found.

  * When I force **_Path to Pylint executable_** to **_/usr/bin/pylint_** I have the same issue.

#### Expected Results:

  *  Pylint plugin displays the detected problems

#### Relevant Code:

```
$ which pylint
/usr/bin/pylint
```

**Comment by SergeyKapshuchenko** [comment]
same problem, any suggestions ?

**Comment by MrBerthier** [comment]
Unfortunately, I have no workaround for now. Please let me know if you find something!

**Comment by SergeyKapshuchenko** [comment]
@MrBerthier so I've fixed it

1. pip uninstall pylint
2. pip install pylint -  I get error about:
 "No metadata found in ./.local/lib/python3.9/site-packages
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/venv/lib/python3.9/site-packages/pylint-2.10.2.dist-info/METADATA'"
3. delete folders "pylint" and "pylint-{version}.dist-info" in /venv/lib/python{version}/...
4. try to pip install pylint again

Now everything works fine

**Comment by MrBerthier** [comment]
Thanks!

**Comment by fzyzcjy** [comment]
I am facing the same problem in https://github.com/leinardi/pylint-pycharm/issues/89. Could you please provide some suggestions?

**Comment by ewagner-verta** [comment]
Same problem.  The plugin simply will not recognize any pylons executable.  I've ripped out and reinstalled pylons.  I've tried using the local 'usr/local/bin/pylint' with no luck.

PyCharm 2022.2.3, Pylint Plugin 0.14.0
